---

postfix_slave: "no"
smtp_email: example@test.local
smtp_password: "1234567890"
smtp_server: smtp.example.local
smtp_port: 587
smtp_pass: 
postfix_networks:
  - "10.0.0.0/8"
  - "172.16.0.0/16"
  - "192.168.1.0/24"
