---
# roles/postfix/tasks/postfix_install.yml: Installation 'postfix' role. Called by main.yml
# Load a variable file based on the OS type, or a default if not found.

- debug: var=ansible_os_family

- name: Install Postfix Package
  package: 
    name: "{{ postfix_package }}"
    state: latest
  # Implied enable service
  notify: "Start Postfix Service"

# Usage: echo "sample body of message" | mail -s "Subject" email@example.com
- name: Install Postfix Messaging Package
  package: 
    name: "{{ postfix_messaging_package }}"
    state: latest
